In [ ]:
!pip install numpy sentence-transformers ripser tqdm requests pandas statsmodels stargazer

In [ ]:
!pip install transformers==4.51.3 torch accelerate

In [ ]:
!pip install vllm

# Сбор графов

In [ ]:
taxonomies = {
    "math": {
        "types": ["Given", "Lemma", "Inference", "Substitution", "Simplification", "Result", "Assumption", "Contradiction"],
        "description": "Математическое рассуждение: дано → лемма → вывод → подстановка → упрощение → результат"
    },
    "law": {
        "types": ["Fact", "Norm", "Precedent", "Inference", "Assumption", "Conclusion", "Contradiction", "ExternalReference"],
        "description": "Юридическое рассуждение: факт → норма права → прецедент → вывод → заключение"
    },
    "general": {
        "types": ["Premise", "Inference", "Assumption", "Evidence", "Conclusion", "Contradiction", "ExternalKnowledge"],
        "description": "Общее логическое рассуждение"
    }
}

def build_taxonomy_prompt(domain="general"):
    tax = taxonomies[domain]
    types_str = ", ".join(tax["types"])
    return f"""Типы узлов: {types_str}
      Описание: {tax['description']}

      Каждый тип означает:
      - Given/Fact: исходные данные, не требующие доказательства
      - Lemma/Norm: вспомогательное утверждение/норма права
      - Inference: логический переход от одного к другому
      - Assumption: допущение (может быть явным или неявным)
      - Result/Conclusion: финальный ответ
      - Contradiction: обнаруженное противоречие
      - ExternalReference/ExternalKnowledge: ссылка на внешний источник
      """

In [ ]:
import os

from vllm import LLM, SamplingParams
from transformers import AutoTokenizer
from datasets import load_dataset
import torch
import gc
import json
import time
from pathlib import Path
from typing import Any, List
import re
from tqdm import tqdm
import pandas as pd


def ensure_dir(path: str | Path) -> None:
    Path(path).parent.mkdir(parents=True, exist_ok=True)

def setup_vllm_model(model_name: str, gpu_memory_utilization: float = 0.85,
                     max_model_len=5000):

    print(f"Loading {model_name} with vLLM...")

    llm = LLM(
        model=model_name,
        tensor_parallel_size=1,
        trust_remote_code=True,
        max_model_len=max_model_len,
        dtype="float16",
        quantization="awq_marlin",
        gpu_memory_utilization=gpu_memory_utilization,
        disable_log_stats=True,
        enforce_eager=False
    )

    tokenizer = llm.get_tokenizer()
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    print(f"Model loaded successfully")
    return llm, tokenizer

def generate_batch_vllm(
    llm: LLM,
    prompts: List[str],
    max_tokens: int = 3800,
    temperature: float = 0.0
) -> List[str]:
    sampling_params = SamplingParams(
        max_tokens=max_tokens,
        temperature=temperature,
        top_p=1.0,
        top_k=-1,
        stop=None,
        repetition_penalty=1.0
    )


    outputs = llm.generate(prompts, sampling_params)
    responses = [output.outputs[0].text for output in outputs]

    return responses

def build_graph_prompt(question: str, cot: str, text_id, taxonomies, domain: str = "general") -> str:
        tax = taxonomies.get(domain, taxonomies["general"])

        return f"""Ты - Анализатор структуры рассуждений (Reasoning Graph Constructor).

          Задача: из данного Chain‑of‑Thought (CoT) извлечь граф логических элементов, который отражает
          НЕЛИНЕЙНУЮ структуру рассуждений: ветвления, перекрёстные ссылки, контраргументы, уточнения, условные выводы.

          Вопрос: {question}

          Рассуждение (CoT):
          {cot}

          Требования к графу:
          - Узлы (nodes) - очень обобщенные смысловые фрагменты, но не просто формулы или словосочетания,
              а краткое и емкое описание словами того, что происходит внутри шага
          - Рёбра (edges) могут быть любых типов из списка ниже.
          - Граф может быть неацикличным (допустимы обратные связи, повторные использования фактов).
          - Допускаются узлы без связей (если фрагмент изолирован).
          - Добавляй мета-информацию в каждый узел (тип роли: claim, evidence, assumption, rebuttal, synthesis).

          Типы рёбер (relation):
          - SUPPORTS - подтверждает/аргументирует
          - ATTACKS - противоречит / подрывает
          - EQUIV - эквивалентен / переформулирует
          - LEADS_TO - логическое следствие
          - CHALLENGES - ставит под сомнение, но не полностью опровергает
          - REFINES - уточняет / конкретизирует
          - ABSTRACTION - обобщает / абстрагирует
          - IF_TRUE_THEN - условная связь (если A истинно, то следует B)
          - ASSUMES - узел B неявно полагается на A как на предпосылку
          - CONTRADICTS - явное логическое противоречие
          - SYNTHESIS - синтезирует два или более узла в новый вывод
          - PARALLEL - независимые ветки одного уровня (метасвязь)

          Формат вывода - ТОЛЬКО JSON (без пояснений). Отдай ответ в таком виде, чтобы его можно было сразу преобразовать в json в Python.

          Структура:
          {{
            "nodes": [
              {{ "id": "n1", "text": "...", "role": "claim"}},
              {{ "id": "n2", "text": "...", "role": "evidence"}}
            ],
            "edges": [
              {{ "source": "n1", "target": "n2", "relation": "LEADS_TO" }}
            ],
            "metadata": {{
              "has_cycles": false,
              "is_linear": true,
              "total_reasoning_paths": 2
            }}
          }}

          Правила:
          1. Сохраняй порядок, но не принуждай к линейности.
          2. Если один и тот же факт используется в разных частях рассуждения - создавай отдельные узлы ИЛИ одну вершину
          с несколькими входящими/исходящими рёбрами (решай по смыслу).
          3. Не добавляй узлов, которых нет в CoT (не домысливай).
          4. Если тип связи однозначно не определить - ставь "SUPPORTS" или "REFINES"."""

def prepare_prompts(rows: List[dict], tokenizer, prompt: str) -> List[str]:
    prompts = []
    for ex in rows:
        statement = ex.get("statement", "")
        messages=[
                {"role": "system", "content": "Ты аналитик, раскладывающий рассуждения на графы."},
                {"role": "user", "content": prompt}
            ],
        prompt = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
        )
        prompts.append(prompt)
    return prompts

def main():
    model_name = "Qwen/Qwen2.5-32B-Instruct-AWQ"

    print("=" * 60)

    all_prompts = []

    traces_path = "/content/all_traces_math_qwen32b_vllm_final.jsonl"

    out = "/content/llm_graphs_math_qwen2.5_32b_final.jsonl"
    batch_size = 16
    max_new_tokens = 3800

    all_traces = []

    with open(traces_path, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                trace =  json.loads(line)
                all_traces.append(trace)

    traces_df = pd.DataFrame(all_traces)

    print("\n" + "=" * 60)
    print("Setting up main model with vLLM...")
    print("=" * 60)
    model, tokenizer = setup_vllm_model(model_name, gpu_memory_utilization=0.7)
    print("\n" + "=" * 60)
    print("Preparing prompts...")

    all_prompts = []
    for id, row in traces_df.iterrows():
      prompt = build_graph_prompt(row['statement'], row['trace'], row['id'], taxonomies, domain = "math")
      all_prompts.append(prompt)

    rows = [row for _, row in traces_df.iterrows()]

    print("\n" + "=" * 60)
    print(f"Generating responses in batches of {batch_size}...")
    print("=" * 60)

    all_responses = []

    start_total = time.time()

    for batch_start in tqdm(range(len(rows), batch_size), desc="Generating batches"):
        batch_end = min(batch_start + batch_size, len(all_prompts))
        batch_prompts = all_prompts[batch_start:batch_end]
        batch_rows = rows[batch_start:batch_end]

        batch_start_time = time.time()
        try:
            responses = generate_batch_vllm(
                model,
                batch_prompts,
                max_tokens=max_new_tokens,
                temperature=0.0
            )
            gen_time = time.time() - batch_start_time

            for idx, (tr, response) in enumerate(zip(batch_rows, responses)):

                print(f"\nProblem {batch_start + idx + 1}:")
                print(f"Predicted graph: {response}")

                trace = {
                    "id": tr.get("id"),
                    "statement": tr.get("statement"),
                    "model": model_name,
                    "trace": tr.get("trace"),
                    "graph": response,
                    "reference_solution": tr.get("solution"),
                    "is_correct": tr.get("is_correct"),
                    "timestamp": int(time.time()),
                    "processing_time": gen_time / len(batch_prompts)
                }
                all_traces.append(trace)
                all_responses.append(response)

                with open(out, "a", encoding="utf-8") as out_f:
                    out_f.write(json.dumps(trace, ensure_ascii=False) + "\n")
                    out_f.flush()

        except Exception as e:
            print(f"Batch generation error: {e}")
            for ex in batch_rows:
                trace = {
                    "id": ex.get("id"),
                    "statement": ex.get("statement"),
                    "model": model_name,
                    "trace": f"ERROR: {str(e)}",
                    "pred_answer": 'invalid',
                    "final_answer": ex.get("final_answer"),
                    "reference_solution": ex.get("solution"),
                    "is_correct": 'No',
                    "timestamp": int(time.time()),
                    "processing_time": 0
                }
                all_traces.append(trace)
                all_responses.append(('invalid', ex.get("final_answer")))

        if batch_start % (batch_size * 4) == 0:
            print(f"\nGPU memory after batch {batch_start//batch_size + 1}:")
            for i in range(torch.cuda.device_count()):
                allocated = torch.cuda.memory_allocated(i) / 1e9
                print(f"  GPU {i}: {allocated:.2f}GB allocated")


    total_gen_time = time.time() - start_total


    print("\n" + "=" * 60)
    print("FINAL STATISTICS")
    print("=" * 60)

    print(f"Total problems: {len(all_traces)}")

    print(f"\nGeneration speed: {len(all_traces)/total_gen_time:.2f} samples/sec")
    print(f"\nResults saved to: {out}")

if __name__ == "__main__":
    main()

In [ ]:
from google.colab import files

files.download('/content/llm_graphs_math_qwen2.5_32b_final.jsonl')

# Парсинг графа

In [ ]:
import pandas as pd
import json

llm_graphs_df = pd.read_csv('/content/llm_graphs_math_qwen2.5_32b_final.csv')

In [ ]:
def extract_json(text):
    brace_count = 0
    start = None

    for i, char in enumerate(text):
        if char == '{':
            if brace_count == 0:
                start = i
            brace_count += 1
        elif char == '}':
            brace_count -= 1
            if brace_count == 0 and start is not None:
                json_str = text[start:i+1]
                try:
                    return json.loads(json_str)
                except json.JSONDecodeError:
                    continue
    return 'invalid'

In [ ]:
def is_path_graph(G):

    G_und = G.to_undirected()
    if not nx.is_connected(G_und):
        return False

    if nx.number_of_selfloops(G) > 0:
        return False

    odd_degree_nodes = [v for v, degree in G.degree() if degree != 2]
    if len(odd_degree_nodes) == 0 and G.number_of_nodes() == 1:
        return True

    degrees = [d for n, d in G.degree()]
    if set(degrees) not in [{1}, {2}, {1, 2}]:
        return False

    if degrees.count(1) == 2:
        return True
    else:
        return False

In [ ]:
llm_graphs_df['graph'] = llm_graphs_df['graph'].apply(lambda text: extract_json(text))

In [ ]:
llm_graphs_df[llm_graphs_df['graph'] == 'invalid']

,Unnamed: 0,id,statement,model,trace,graph,reference_solution,is_correct,timestamp,processing_time
8,8,9,The sequence of integers in the row of squares...,Qwen/Qwen2.5-32B-Instruct-AWQ,"To solve the problem, we need to determine th...",invalid,NaN,No,1778932026,1.906247
9,9,10,Tim wants to invest some money in a bank which...,Qwen/Qwen2.5-32B-Instruct-AWQ,"To solve this problem, we need to use the for...",invalid,NaN,No,1778932026,1.906247
11,11,12,Consider the given functions: $$\begin{array}{...,Qwen/Qwen2.5-32B-Instruct-AWQ,To solve for the value of \( k \) given the f...,invalid,NaN,Yes,1778932026,1.906247
81,81,82,Compute $\frac{x^8+12x^4+36}{x^4+6}$ when $x=5$.,Qwen/Qwen2.5-32B-Instruct-AWQ,"To solve the problem, we will follow these st...",invalid,NaN,Yes,1778932141,1.457989
111,111,112,"If $x$, $y$, and $z$ are positive numbers sati...",Qwen/Qwen2.5-32B-Instruct-AWQ,To solve for \(xyz\) given the equations:\n\[...,invalid,NaN,Yes,1778932164,1.396631
...,...,...,...,...,...,...,...,...,...,...
12388,5972,5282,"Consider a string of $n$ $7$'s, $7777\cdots77,...",Qwen/Qwen2.5-32B-Instruct-AWQ,\n\nStep 1: Understanding the problem\nWe are...,invalid,NaN,No,1778970599,2.353718
12390,5974,5284,Three clever monkeys divide a pile of bananas....,Qwen/Qwen2.5-32B-Instruct-AWQ,\n\nLet's denote the total number of bananas ...,invalid,NaN,No,1778970599,2.353718
12414,5998,5308,Define $n!!$ to be $n(n-2)(n-4)\cdots 3\cdot 1...,Qwen/Qwen2.5-32B-Instruct-AWQ,\n\nStep 1: Understanding the Double Factoria...,invalid,NaN,No,1778970633,2.153590
12415,5999,5309,Let $N$ be the number of ways to write $2010$ ...,Qwen/Qwen2.5-32B-Instruct-AWQ,"To solve the problem, we need to find the num...",invalid,NaN,No,1778970633,2.153590
12424,5,6502,Find the greatest common divisor of 12 and 20.,Qwen/Qwen2.5-32B-Instruct-AWQ,To find the greatest common divisor (GCD) of ...,invalid,NaN,Yes,1778972638,4.338803

In [ ]:
llm_graphs_df[llm_graphs_df['id'] == 735]['graph'].values[0]

{'nodes': [{'id': 'n1',
   'text': 'Substitute a = 2 into the product',
   'role': 'evidence'},
  {'id': 'n2',
   'text': 'Identify the terms in the product',
   'role': 'evidence'},
  {'id': 'n3',
   'text': 'Determine if any of the terms are zero',
   'role': 'evidence'},
  {'n4': 'n4', 'text': 'The product includes the term 0', 'role': 'evidence'},
  {'n5': 'n5',
   'text': 'Any number multiplied by zero is zero',
   'role': 'evidence'},
  {'n6': 'n6', 'text': 'The value of the product is 0', 'role': 'claim'}],
 'edges': [{'source': 'n1', 'target': 'n2', 'relation': 'LEADS_TO'},
  {'source': 'n2', 'target': 'n3', 'relation': 'LEADS_TO'},
  {'source': 'n3', 'target': 'n4', 'relation': 'SUPPORTS'},
  {'source': 'n4', 'target': 'n5', 'relation': 'SUPPORTS'},
  {'source': 'n5', 'target': 'n6', 'relation': 'LEADS_TO'}],
 'metadata': {'has_cycles': False,
  'is_linear': True,
  'total_reasoning_paths': 1}}

In [ ]:
llm_graphs_df.head(5)

,Unnamed: 0,id,statement,model,trace,graph,reference_solution,is_correct,timestamp,processing_time
0,0,1,"Let \[f(x) = \left\{\n\begin{array}{cl} ax+3, ...",Qwen/Qwen2.5-32B-Instruct-AWQ,To ensure the piecewise function \( f(x) \) i...,"{'nodes': [{'id': 'n1', 'text': 'Check continu...",NaN,Yes,1778932026,1.906247
1,1,2,A rectangular band formation is a formation wi...,Qwen/Qwen2.5-32B-Instruct-AWQ,"To solve the problem, we need to find the lar...","{'nodes': [{'id': 'n1', 'text': 'Initial forma...",NaN,Yes,1778932026,1.906247
2,2,3,What is the degree of the polynomial $(4 +5x^3...,Qwen/Qwen2.5-32B-Instruct-AWQ,To determine the degree of the polynomial \(4...,"{'nodes': [{'id': 'n1', 'text': 'Combine const...",NaN,Yes,1778932026,1.906247
3,3,4,Evaluate $\left\lceil3\left(6-\frac12\right)\r...,Qwen/Qwen2.5-32B-Instruct-AWQ,To evaluate the expression \(\left\lceil3\lef...,"{'nodes': [{'id': 'n1', 'text': 'Evaluate the ...",NaN,Yes,1778932026,1.906247
4,4,5,Sam is hired for a 20-day period. On days that...,Qwen/Qwen2.5-32B-Instruct-AWQ,"To solve the problem, we need to determine ho...","{'id': 'n1', 'text': 'Define variables for day...",NaN,Yes,1778932026,1.906247

In [ ]:
llm_graphs_df['is_correct'].value_counts()

is_correct
Yes    10132
No      2368
Name: count, dtype: int64

In [ ]:
llm_graphs_df['is_correct']

0        Yes
1        Yes
2        Yes
3        Yes
4        Yes
        ...
12495    Yes
12496    Yes
12497    Yes
12498    Yes
12499    Yes
Name: is_correct, Length: 12500, dtype: object

In [ ]:
from dataclasses import dataclass
from typing import Iterable, Optional
from sentence_transformers import SentenceTransformer
import numpy as np


@dataclass
class EmbeddingConfig:
    model_name: str = "sentence-transformers/all-mpnet-base-v2"
    batch_size: int = 32
    device: Optional[str] = None


class SentenceTransformerEmbedder:

    def __init__(self, cfg: EmbeddingConfig):
        self.cfg = cfg or EmbeddingConfig()
        self.model = SentenceTransformer(self.cfg.model_name, device=self.cfg.device)

    def encode(self, texts: Iterable[str]) -> np.ndarray:
        arr = self.model.encode(
            list(texts),
            batch_size=self.cfg.batch_size,
            convert_to_numpy=True,
            normalize_embeddings=True,

        )
        return np.asarray(arr)


def cosine_similarity_matrix(X: np.ndarray) -> np.ndarray:
    Xn = X / (np.linalg.norm(X, axis=1, keepdims=True) + 1e-12)
    return Xn @ Xn.T

In [ ]:
import networkx as nx

In [ ]:
model_name = "sentence-transformers/all-mpnet-base-v2"
device = "cuda"

embedder = SentenceTransformerEmbedder(
        EmbeddingConfig(model_name=model_name, device=device)
    )

In [ ]:
from sklearn.metrics.pairwise import cosine_distances

def load_graph_json(llm_graphs_df, graph_id, embedder):

    G = nx.DiGraph()
    row = llm_graphs_df[llm_graphs_df.id == graph_id]

    is_correct = True
    is_path = None

    if 'nodes' in row['graph'].values[0]:
      for idx, node in enumerate(row['graph'].values[0]['nodes']):
          if 'id' in node:
            embedding = embedder.encode([node['text']])
            embedding = embedding.reshape(embedding.shape[1])
            G.add_node(node['id'], embedding = embedding)
          else:
            is_correct = False

      if is_correct:
        for idx, edge in enumerate(row['graph'].values[0]['edges']):
            u, v = edge['source'], edge['target']
            if u in G.nodes and v in G.nodes():
              weight = cosine_distances([G.nodes[u]['embedding']], [G.nodes[v]['embedding']])[0][0]
              G.add_edge(u, v, weight=float(weight))

        is_path = is_path_graph(G)

    return {
        'graph': G,
        'num_nodes': len(G.nodes()),
        'num_edges': len(G.edges()),
        'is_path': is_path
    }

In [ ]:
import json
import pandas as pd
import scipy.sparse as sp
import pickle
from tqdm import tqdm
from pathlib import Path

def ensure_dir(path: str | Path) -> None:
    Path(path).parent.mkdir(parents=True, exist_ok=True)

traces_path = '/content/all_traces_math_qwen32b_vllm_final.jsonl'
traces = []

with open(traces_path, 'r') as f:
    for line in f:
      if line.strip():
          trace = json.loads(line)
          traces.append(trace)

traces_df = pd.DataFrame(traces)

for id in tqdm(enumerate(traces_df['id'].tolist())):
  graph_data = load_graph_json(llm_graphs_df, id[1], embedder)
  if graph_data['num_nodes'] > 0 and graph_data['num_edges'] > 0 and graph_data['is_path'] == False:
    pid = str(id[1]).replace('/', '_')
    graph_path = Path('graph_dir')/ f'{pid}.pkl'
    G = graph_data['graph']
    ensure_dir(graph_path)
    with open(graph_path, 'wb') as f:
        pickle.dump(G, f, protocol=pickle.HIGHEST_PROTOCOL)

12500it [20:23, 10.21it/s]

In [ ]:
llm_graphs_df

,Unnamed: 0,id,statement,model,trace,graph,reference_solution,is_correct,timestamp,processing_time
0,0,1,"Let \[f(x) = \left\{\n\begin{array}{cl} ax+3, ...",Qwen/Qwen2.5-32B-Instruct-AWQ,To ensure the piecewise function \( f(x) \) i...,"{'nodes': [{'id': 'n1', 'text': 'Check continu...",NaN,Yes,1778932026,1.906247
1,1,2,A rectangular band formation is a formation wi...,Qwen/Qwen2.5-32B-Instruct-AWQ,"To solve the problem, we need to find the lar...","{'nodes': [{'id': 'n1', 'text': 'Initial forma...",NaN,Yes,1778932026,1.906247
2,2,3,What is the degree of the polynomial $(4 +5x^3...,Qwen/Qwen2.5-32B-Instruct-AWQ,To determine the degree of the polynomial \(4...,"{'nodes': [{'id': 'n1', 'text': 'Combine const...",NaN,Yes,1778932026,1.906247
3,3,4,Evaluate $\left\lceil3\left(6-\frac12\right)\r...,Qwen/Qwen2.5-32B-Instruct-AWQ,To evaluate the expression \(\left\lceil3\lef...,"{'nodes': [{'id': 'n1', 'text': 'Evaluate the ...",NaN,Yes,1778932026,1.906247
4,4,5,Sam is hired for a 20-day period. On days that...,Qwen/Qwen2.5-32B-Instruct-AWQ,"To solve the problem, we need to determine ho...","{'id': 'n1', 'text': 'Define variables for day...",NaN,Yes,1778932026,1.906247
...,...,...,...,...,...,...,...,...,...,...
12495,76,6573,A $2\times 3$ rectangle and a $3\times 4$ rect...,Qwen/Qwen2.5-32B-Instruct-AWQ,To find the smallest possible area of the squ...,"{'nodes': [{'id': 'n1', 'text': 'Determine the...",NaN,Yes,1778972726,1.270443
12496,77,6574,"Amanda, Ben, and Carlos share a sum of money. ...",Qwen/Qwen2.5-32B-Instruct-AWQ,"To solve the problem, we will follow these st...","{'nodes': [{'id': 'n1', 'text': 'Identify the ...",NaN,Yes,1778972726,1.270443
12497,78,6575,A round-robin tennis tournament consists of ea...,Qwen/Qwen2.5-32B-Instruct-AWQ,To determine the number of matches in an 8-pe...,"{'nodes': [{'id': 'n1', 'text': 'Identify the ...",NaN,Yes,1778972726,1.270443
12498,79,6576,"Eugene, Brianna, and Katie are going on a run....",Qwen/Qwen2.5-32B-Instruct-AWQ,"To determine how fast Katie runs, we need to ...","{'nodes': [{'id': 'n1', 'text': 'Eugene runs a...",NaN,Yes,1778972726,1.270443
12499,80,6577,If infinitely many values of $y$ satisfy the e...,Qwen/Qwen2.5-32B-Instruct-AWQ,"To solve the problem, we start by simplifying...","{'nodes': [{'id': 'n1', 'text': 'Distribute th...",NaN,Yes,1778972750,1.510651

In [ ]:
!zip -r llm_graphs_pickle_math_Qwen2.5_32B.zip graph_dir

In [ ]:
!unzip /content/llm_graphs_pickle_math_Qwen2.5_32B.zip -d .

In [ ]:
!pip install torch_geometric
!pip install networkx

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import GCNConv, GATConv, global_mean_pool

class GNNBinaryClassifier(nn.Module):
    def __init__(self, input_dim, hidden_dim):
        super().__init__()
        self.conv1 = GCNConv(input_dim, hidden_dim)
        self.conv2 = GCNConv(hidden_dim, hidden_dim)
        self.classifier = nn.Linear(hidden_dim, 1)

    def forward(self, x, edge_index, edge_weight, batch):
        x = self.conv1(x, edge_index, edge_weight)
        x = F.relu(x)
        x = self.conv2(x, edge_index, edge_weight)
        graph_embedding = global_mean_pool(x, batch)
        out = self.classifier(graph_embedding)
        return out

In [ ]:
import torch
from torch.utils.data import Dataset
from torch_geometric.data import Data as PyGData
from torch_geometric.data import Batch
from torch_geometric.loader import DataLoader
from sklearn.metrics.pairwise import cosine_distances
import networkx as nx
import os
import json
import pandas as pd
import numpy as np
import pickle

class GraphBinaryDataset(Dataset):

    def __init__(self, dataset, graph_dir, traces_path, preload=False, transform=None):
        self.dataset = dataset
        self.graph_dir = graph_dir
        self.transform = transform
        self.preload = preload

        self.graph_files = [f for f in os.listdir(graph_dir)
                           if f.endswith(('.graphml')) or f.endswith(('.pkl')) ]

        print(self.graph_files)

        if os.path.exists(traces_path):
            traces = []
            with open(traces_path, 'r') as f:
               for line in f:
                  if line.strip():
                      trace = json.loads(line)
                      traces.append(trace)

            traces_df = pd.DataFrame(traces)
            traces_df['is_correct'] = traces_df.apply(lambda x: 'Yes' if (x.is_correct == 'Yes') else 'No', axis = 1)
            traces_df['is_correct'] = traces_df['is_correct'].apply(lambda x: 0.0 if x == 'Yes' else 1.0)
            self.traces = traces_df[['id', 'is_correct']]

        if preload:
            print("Preloading all graphs into memory...")
            self.data = []
            for idx in range(len(self.graph_files)):
                if idx % 100 == 0:
                    print(f"  Loading {idx}/{len(self.graph_files)}")
                pyg_data, label = self._load_item(idx)
                self.data.append((pyg_data, label))
            print(f"Preloaded {len(self.data)} graphs")


    def __len__(self):
        return len(self.graph_files)

    def _load_item(self, idx):
        graph_file = self.graph_files[idx]
        graph_path = os.path.join(self.graph_dir, graph_file)

        if self.dataset == 'math500':
            id = graph_file.split('.')[0]
            self.traces['id'] = self.traces['id'].apply(lambda x: x.replace('/', '_').split('.')[0])
            label = self.traces[self.traces.id == id]['is_correct'].values[0]
        else:
            id = graph_path.split('.')[0].split('/')[1]
            label = self.traces[self.traces.id == int(id)]['is_correct'].values[0]

        if graph_file.endswith('.graphml'):
          G = nx.read_gml(graph_path)
        if graph_file.endswith('.pkl'):
          with open(graph_path, 'rb') as f:
            G = pickle.load(f)

        pyg_data = self._nx_to_pyg(G)

        if isinstance(label, (int, float)):
            label = torch.tensor([label], dtype=torch.float32)

        return pyg_data, label

    def __getitem__(self, idx):
        if self.preload:
            pyg_data, label = self.data[idx]
            return pyg_data, label.clone() if isinstance(label, torch.Tensor) else label
        else:
            return self._load_item(idx)

    def _nx_to_pyg(self, G, edge_metric=None):

        nodes = list(G.nodes())

        node_to_idx = {node: i for i, node in enumerate(nodes)}


        node_features = []
        for node in nodes:
            if 'embedding' in G.nodes[node]:
                feat = np.array(G.nodes[node]['embedding'])

            node_features.append(feat)


        node_features = np.array(node_features)

        x = torch.tensor(node_features, dtype=torch.float)

        edges = []
        edge_weights = []

        for u, v in G.edges():

            edges.append([node_to_idx[u], node_to_idx[v]])
            if edge_metric:
              weight = cosine_distances([G.nodes[u]['embedding']], [G.nodes[v]['embedding']])[0][0]
            else:
              weight = G[u][v].get('weight', 1.0)

            edge_weights.append(weight)

            if not G.is_directed():
                edges.append([node_to_idx[v], node_to_idx[u]])
                edge_weights.append(weight)

        edge_index = torch.tensor(edges, dtype=torch.long).t().contiguous()
        edge_weight = torch.tensor(edge_weights, dtype=torch.float) if edge_weights else None

        pyg_data = PyGData(x=x, edge_index=edge_index, edge_weight=edge_weight)

        return pyg_data


def main():
    GRAPH_DIR = 'graph_dir'
    traces_path = '/content/all_traces_math_qwen32b_vllm_final.jsonl'
    dataset = GraphBinaryDataset('math', GRAPH_DIR, traces_path)
    train_size = int(0.7 * len(dataset))
    val_size = int(0.1 * len(dataset))
    test_size = len(dataset) - train_size - val_size

    train_dataset, val_dataset, test_dataset = torch.utils.data.random_split(
        dataset, [train_size, val_size, test_size]
    )

    BATCH_SIZE = 32

    train_loader = DataLoader(
        train_dataset,
        batch_size=BATCH_SIZE,
        shuffle=True,
        num_workers=2
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        num_workers=2
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        num_workers=2
    )

    return dataset, train_loader, val_loader, test_loader


if __name__ == "__main__":
    dataset, train_loader, val_loader, test_loader = main()

['6835.pkl', '10236.pkl', '8817.pkl', '5706.pkl', '7249.pkl', '9962.pkl', '5666.pkl', '4391.pkl', '11573.pkl', '9952.pkl', '12251.pkl', '10277.pkl', '317.pkl', '248.pkl', '1292.pkl', '6380.pkl', '10946.pkl', '4670.pkl', '6037.pkl', '9004.pkl', '1820.pkl', '6959.pkl', '3833.pkl', '9323.pkl', '4580.pkl', '9961.pkl', '3610.pkl', '3007.pkl', '8501.pkl', '8769.pkl', '12029.pkl', '1810.pkl', '4217.pkl', '2264.pkl', '10427.pkl', '1414.pkl', '1741.pkl', '3430.pkl', '1365.pkl', '3229.pkl', '12203.pkl', '7766.pkl', '9610.pkl', '3779.pkl', '718.pkl', '6179.pkl', '1876.pkl', '5239.pkl', '11480.pkl', '2354.pkl', '11555.pkl', '10450.pkl', '9042.pkl', '10084.pkl', '998.pkl', '10051.pkl', '5646.pkl', '6708.pkl', '9835.pkl', '9000.pkl', '10951.pkl', '5017.pkl', '5062.pkl', '2986.pkl', '6347.pkl', '125.pkl', '6553.pkl', '4869.pkl', '2300.pkl', '8776.pkl', '9329.pkl', '10043.pkl', '3688.pkl', '9321.pkl', '8003.pkl', '2682.pkl', '3732.pkl', '8885.pkl', '6917.pkl', '3859.pkl', '10922.pkl', '1650.pkl', '1257.pkl', '5915.pkl', '2684.pkl', '1728.pkl', '9376.pkl', '8669.pkl', '1139.pkl', '6058.pkl', '6213.pkl', '9515.pkl', '5834.pkl', '1421.pkl', '996.pkl', '10613.pkl', '2124.pkl', '6820.pkl', '10007.pkl', '11509.pkl', '9405.pkl', '7524.pkl', '295.pkl', '119.pkl', '9204.pkl', '754.pkl', '8805.pkl', '12068.pkl', '2852.pkl', '9442.pkl', '7349.pkl', '9389.pkl', '152.pkl', '11928.pkl', '8939.pkl', '1532.pkl', '11179.pkl', '1806.pkl', '4836.pkl', '1913.pkl', '11023.pkl', '3369.pkl', '6507.pkl', '10616.pkl', '414.pkl', '9885.pkl', '2369.pkl', '4651.pkl', '10938.pkl', '3671.pkl', '5194.pkl', '12097.pkl', '1887.pkl', '3603.pkl', '1129.pkl', '4487.pkl', '6134.pkl', '1468.pkl', '8919.pkl', '8806.pkl', '11971.pkl', '5108.pkl', '1452.pkl', '1816.pkl', '8356.pkl', '10957.pkl', '4983.pkl', '5278.pkl', '1821.pkl', '4446.pkl', '12274.pkl', '7664.pkl', '11719.pkl', '12276.pkl', '8696.pkl', '8938.pkl', '6001.pkl', '11566.pkl', '6784.pkl', '6086.pkl', '10602.pkl', '11682.pkl', '11361.pkl', '11729.pkl', '6233.pkl', '10377.pkl', '6970.pkl', '7632.pkl', '11769.pkl', '10432.pkl', '8034.pkl', '8869.pkl', '2435.pkl', '4817.pkl', '10624.pkl', '8424.pkl', '12222.pkl', '10531.pkl', '6226.pkl', '11717.pkl', '6998.pkl', '11594.pkl', '3570.pkl', '3300.pkl', '6525.pkl', '12392.pkl', '455.pkl', '4150.pkl', '2524.pkl', '11564.pkl', '10228.pkl', '7118.pkl', '8326.pkl', '9585.pkl', '9965.pkl', '12497.pkl', '8230.pkl', '1372.pkl', '9621.pkl', '12269.pkl', '1784.pkl', '7595.pkl', '10404.pkl', '3290.pkl', '1476.pkl', '6164.pkl', '6051.pkl', '2017.pkl', '6827.pkl', '5846.pkl', '6554.pkl', '321.pkl', '3440.pkl', '2430.pkl', '505.pkl', '11993.pkl', '2177.pkl', '5658.pkl', '1597.pkl', '10589.pkl', '5726.pkl', '9255.pkl', '2887.pkl', '6028.pkl', '4347.pkl', '541.pkl', '949.pkl', '8908.pkl', '3679.pkl', '1429.pkl', '2402.pkl', '94.pkl', '2406.pkl', '8767.pkl', '11814.pkl', '2541.pkl', '5623.pkl', '10595.pkl', '4395.pkl', '5874.pkl', '6845.pkl', '6474.pkl', '4799.pkl', '2422.pkl', '7778.pkl', '5859.pkl', '4935.pkl', '9309.pkl', '7078.pkl', '10622.pkl', '8892.pkl', '2367.pkl', '10899.pkl', '8494.pkl', '3696.pkl', '5144.pkl', '3911.pkl', '8663.pkl', '6133.pkl', '2970.pkl', '4358.pkl', '11781.pkl', '9245.pkl', '9009.pkl', '6931.pkl', '11397.pkl', '4832.pkl', '3881.pkl', '4398.pkl', '6435.pkl', '4110.pkl', '1386.pkl', '9355.pkl', '8684.pkl', '8037.pkl', '6353.pkl', '1264.pkl', '5901.pkl', '8553.pkl', '7933.pkl', '1241.pkl', '11033.pkl', '7469.pkl', '3720.pkl', '6772.pkl', '6615.pkl', '8876.pkl', '2785.pkl', '2064.pkl', '2152.pkl', '374.pkl', '3026.pkl', '9064.pkl', '4904.pkl', '2288.pkl', '7254.pkl', '9356.pkl', '5014.pkl', '6691.pkl', '2733.pkl', '8161.pkl', '11913.pkl', '6039.pkl', '12198.pkl', '720.pkl', '11306.pkl', '1445.pkl', '9896.pkl', '4831.pkl', '8823.pkl', '206.pkl', '9521.pkl', '617.pkl', '3340.pkl', '3992.pkl', '12270.pkl', '11218.pkl', '84.pkl', '8412.pkl', '11767.pkl', '929.pkl', '5948.pkl', '2196.pkl', '3394.pkl', '7203.pkl', '7144.pkl', '3786.pkl', '2491.pkl', '2880.pkl', '6556.pkl', '1894.pkl', '3748.pkl', '7431.pkl', '3796.pkl', '10049.pkl', '5645.pkl', '6010.pkl', '6598.pkl', '6501.pkl', '3654.pkl', '4424.pkl', '7482.pkl', '1325.pkl', '6517.pkl', '7445.pkl', '2870.pkl', '10799.pkl', '5717.pkl', '12383.pkl', '8188.pkl', '12226.pkl', '2132.pkl', '2499.pkl', '7023.pkl', '560.pkl', '10592.pkl', '1716.pkl', '4182.pkl', '5544.pkl', '6916.pkl', '3706.pkl', '11857.pkl', '1253.pkl', '7622.pkl', '8135.pkl', '11726.pkl', '7206.pkl', '5555.pkl', '3907.pkl', '11645.pkl', '4037.pkl', '1098.pkl', '11672.pkl', '12424.pkl', '11987.pkl', '1263.pkl', '5025.pkl', '3968.pkl', '943.pkl', '12107.pkl', '6019.pkl', '5966.pkl', '8773.pkl', '3425.pkl', '10241.pkl', '6244.pkl', '11701.pkl', '7208.pkl', '7468.pkl', '9997.pkl', '5085.pkl', '6394.pkl', '12385.pkl', '1074.pkl', '4476.pkl', '664.pkl', '10307.pkl', '9696.pkl', '69.pkl', '4407.pkl', '6595.pkl', '8986.pkl', '4149.pkl', '11618.pkl', '4856.pkl', '3563.pkl', '4959.pkl', '4076.pkl', '7591.pkl', '5090.pkl', '6322.pkl', '9016.pkl', '7270.pkl', '1039.pkl', '3474.pkl', '8215.pkl', '11694.pkl', '11424.pkl', '12088.pkl', '11981.pkl', '8571.pkl', '8581.pkl', '1093.pkl', '2814.pkl', '7951.pkl', '1334.pkl', '9339.pkl', '5494.pkl', '8226.pkl', '2652.pkl', '413.pkl', '5776.pkl', '4372.pkl', '4611.pkl', '6237.pkl', '10839.pkl', '9464.pkl', '11891.pkl', '12380.pkl', '6188.pkl', '1092.pkl', '1796.pkl', '5876.pkl', '189.pkl', '7521.pkl', '2046.pkl', '5611.pkl', '7008.pkl', '3970.pkl', '10475.pkl', '4091.pkl', '11292.pkl', '8313.pkl', '1288.pkl', '7614.pkl', '221.pkl', '6851.pkl', '11724.pkl', '7954.pkl', '2762.pkl', '11018.pkl', '1381.pkl', '8893.pkl', '11045.pkl', '6893.pkl', '9135.pkl', '2107.pkl', '7111.pkl', '6869.pkl', '3346.pkl', '1014.pkl', '3347.pkl', '3521.pkl', '6786.pkl', '9943.pkl', '5564.pkl', '9378.pkl', '11738.pkl', '2066.pkl', '1640.pkl', '2151.pkl', '6290.pkl', '7631.pkl', '1085.pkl', '8743.pkl', '1699.pkl', '7090.pkl', '304.pkl', '2841.pkl', '1053.pkl', '6406.pkl', '6262.pkl', '8969.pkl', '4461.pkl', '1141.pkl', '3214.pkl', '3644.pkl', '1732.pkl', '7402.pkl', '5970.pkl', '4953.pkl', '9935.pkl', '8989.pkl', '4542.pkl', '10813.pkl', '4989.pkl', '3284.pkl', '8487.pkl', '6444.pkl', '4315.pkl', '3132.pkl', '8703.pkl', '6216.pkl', '3920.pkl', '2376.pkl', '8727.pkl', '4279.pkl', '1829.pkl', '7496.pkl', '4156.pkl', '5562.pkl', '12007.pkl', '9280.pkl', '7801.pkl', '10099.pkl', '10872.pkl', '2796.pkl', '3519.pkl', '10093.pkl', '467.pkl', '10511.pkl', '3317.pkl', '2686.pkl', '7388.pkl', '10155.pkl', '10665.pkl', '11119.pkl', '950.pkl', '2921.pkl', '8894.pkl', '10230.pkl', '7529.pkl', '2665.pkl', '8209.pkl', '5582.pkl', '8680.pkl', '8968.pkl', '4443.pkl', '11465.pkl', '10150.pkl', '2555.pkl', '1582.pkl', '10554.pkl', '3257.pkl', '12233.pkl', '10877.pkl', '10346.pkl', '4901.pkl', '4718.pkl', '11697.pkl', '11666.pkl', '4992.pkl', '5499.pkl', '250.pkl', '4781.pkl', '10231.pkl', '1598.pkl', '7044.pkl', '2482.pkl', '11105.pkl', '8220.pkl', '4874.pkl', '3437.pkl', '11426.pkl', '11215.pkl', '3184.pkl', '4780.pkl', '11812.pkl', '5720.pkl', '2917.pkl', '9819.pkl', '8912.pkl', '3782.pkl', '940.pkl', '10050.pkl', '5316.pkl', '3330.pkl', '9931.pkl', '10399.pkl', '6398.pkl', '3562.pkl', '11177.pkl', '176.pkl', '9596.pkl', '10780.pkl', '7241.pkl', '1957.pkl', '10420.pkl', '7405.pkl', '4786.pkl', '8223.pkl', '3451.pkl', '5635.pkl', '5576.pkl', '9056.pkl', '6060.pkl', '8261.pkl', '7181.pkl', '3269.pkl', '6544.pkl', '12493.pkl', '934.pkl', '11535.pkl', '117.pkl', '7069.pkl', '1237.pkl', '661.pkl', '4308.pkl', '9430.pkl', '5158.pkl', '4750.pkl', '2565.pkl', '6059.pkl', '5674.pkl', '4234.pkl', '5163.pkl', '8267.pkl', '7791.pkl', '8077.pkl', '9825.pkl', '8164.pkl', '7162.pkl', '4859.pkl', '4071.pkl', '1881.pkl', '2889.pkl', '4618.pkl', '12172.pkl', '7959.pkl', '12246.pkl', '6432.pkl', '12183.pkl', '9527.pkl', '12201.pkl', '2574.pkl', '9012.pkl', '5687.pkl', '7417.pkl', '4710.pkl', '2590.pkl', '1949.pkl', '6317.pkl', '6680.pkl', '717.pkl', '8519.pkl', '3885.pkl', '11820.pkl', '1684.pkl', '9209.pkl', '3594.pkl', '3998.pkl', '9149.pkl', '6.pkl', '10279.pkl', '11446.pkl', '9564.pkl', '3502.pkl', '8116.pkl', '5600.pkl', '5522.pkl', '11447.pkl', '6688.pkl', '4840.pkl', '3705.pkl', '5528.pkl', '11066.pkl', '6683.pkl', '9313.pkl', '2750.pkl', '11962.pkl', '10995.pkl', '1140.pkl', '4608.pkl', '9693.pkl', '5328.pkl', '185.pkl', '8391.pkl', '10998.pkl', '2781.pkl', '2688.pkl', '3690.pkl', '4099.pkl', '11227.pkl', '6255.pkl', '8558.pkl', '12477.pkl', '5354.pkl', '2757.pkl', '2614.pkl', '2566.pkl', '3131.pkl', '3823.pkl', '5045.pkl', '6518.pkl', '11003.pkl', '5457.pkl', '6662.pkl', '102.pkl', '8321.pkl', '5468.pkl', '7099.pkl', '10919.pkl', '7032.pkl', '2753.pkl', '12095.pkl', '10537.pkl', '9443.pkl', '8142.pkl', '3467.pkl', '50.pkl', '10419.pkl', '7528.pkl', '1088.pkl', '308.pkl', '861.pkl', '8225.pkl', '345.pkl', '2004.pkl', '12308.pkl', '6374.pkl', '3978.pkl', '8815.pkl', '4131.pkl', '4528.pkl', '8842.pkl', '9018.pkl', '9663.pkl', '3264.pkl', '11952.pkl', '33.pkl', '2.pkl', '5983.pkl', '6360.pkl', '11378.pkl', '953.pkl', '10434.pkl', '9741.pkl', '7494.pkl', '10950.pkl', '9722.pkl', '9930.pkl', '1101.pkl', '10611.pkl', '2677.pkl', '2290.pkl', '9753.pkl', '9664.pkl', '807.pkl', '6240.pkl', '5170.pkl', '4492.pkl', '2864.pkl', '3628.pkl', '2220.pkl', '863.pkl', '2228.pkl', '894.pkl', '10446.pkl', '11936.pkl', '1523.pkl', '11135.pkl', '3661.pkl', '12127.pkl', '401.pkl', '3263.pkl', '9898.pkl', '11335.pkl', '10861.pkl', '7876.pkl', '1639.pkl', '5016.pkl', '6616.pkl', '730.pkl', '404.pkl', '9192.pkl', '10032.pkl', '4385.pkl', '5820.pkl', '12046.pkl', '6668.pkl', '10591.pkl', '10753.pkl', '3893.pkl', '4908.pkl', '6609.pkl', '9736.pkl', '5777.pkl', '10282.pkl', '1402.pkl', '12460.pkl', '5306.pkl', '4946.pkl', '5973.pkl', '11152.pkl', '875.pkl', '2554.pkl', '2959.pkl', '4390.pkl', '7999.pkl', '10378.pkl', '1705.pkl', '7640.pkl', '11376.pkl', '8376.pkl', '959.pkl', '742.pkl', '6640.pkl', '1735.pkl', '4302.pkl', '11339.pkl', '4222.pkl', '5486.pkl', '2916.pkl', '9428.pkl', '7568.pkl', '586.pkl', '534.pkl', '4317.pkl', '10140.pkl', '4300.pkl', '12086.pkl', '3903.pkl', '7771.pkl', '2702.pkl', '11874.pkl', '9932.pkl', '4125.pkl', '11389.pkl', '3972.pkl', '2209.pkl', '3525.pkl', '1230.pkl', '9020.pkl', '5742.pkl', '4321.pkl', '7456.pkl', '11452.pkl', '10494.pkl', '5465.pkl', '2850.pkl', '6199.pkl', '12126.pkl', '6186.pkl', '1223.pkl', '6927.pkl', '3817.pkl', '5377.pkl', '294.pkl', '7535.pkl', '7163.pkl', '8640.pkl', '8698.pkl', '2746.pkl', '5391.pkl', '9490.pkl', '2518.pkl', '9798.pkl', '1301.pkl', '3483.pkl', '4820.pkl', '8801.pkl', '788.pkl', '11467.pkl', '11065.pkl', '4854.pkl', '4638.pkl', '12237.pkl', '6442.pkl', '11679.pkl', '4572.pkl', '1711.pkl', '10330.pkl', '12171.pkl', '10251.pkl', '1106.pkl', '10466.pkl', '10354.pkl', '11267.pkl', '10012.pkl', '12257.pkl', '7691.pkl', '10961.pkl', '12463.pkl', '1743.pkl', '6208.pkl', '8375.pkl', '2892.pkl', '6393.pkl', '10878.pkl', '11253.pkl', '5217.pkl', '1391.pkl', '11521.pkl', '3063.pkl', '9418.pkl', '520.pkl', '5234.pkl', '2359.pkl', '5345.pkl', '2080.pkl', '7605.pkl', '3687.pkl', '6821.pkl', '6327.pkl', '6245.pkl', '10187.pkl', '4789.pkl', '10503.pkl', '8383.pkl', '4221.pkl', '1104.pkl', '9210.pkl', '7081.pkl', '8342.pkl', '6872.pkl', '10971.pkl', '7156.pkl', '4349.pkl', '12326.pkl', '12152.pkl', '2823.pkl', '11277.pkl', '4886.pkl', '8741.pkl', '4363.pkl', '8459.pkl', '9620.pkl', '1647.pkl', '127.pkl', '6671.pkl', '8320.pkl', '2384.pkl', '8217.pkl', '4714.pkl', '3332.pkl', '532.pkl', '1322.pkl', '10558.pkl', '6705.pkl', '6801.pkl', '4862.pkl', '12403.pkl', '3271.pkl', '10920.pkl', '3337.pkl', '6093.pkl', '5348.pkl', '2465.pkl', '11162.pkl', '3384.pkl', '10344.pkl', '2825.pkl', '3481.pkl', '10826.pkl', '2550.pkl', '4214.pkl', '3283.pkl', '5557.pkl', '7053.pkl', '1815.pkl', '3756.pkl', '11109.pkl', '9860.pkl', '2386.pkl', '4280.pkl', '8954.pkl', '10398.pkl', '7868.pkl', '5325.pkl', '3235.pkl', '5495.pkl', '5119.pkl', '302.pkl', '2412.pkl', '6829.pkl', '4739.pkl', '1601.pkl', '9622.pkl', '1009.pkl', '9699.pkl', '9746.pkl', '6805.pkl', '9069.pkl', '4774.pkl', '9941.pkl', '8390.pkl', '10401.pkl', '10327.pkl', '10847.pkl', '11363.pkl', '2866.pkl', '2019.pkl', '11225.pkl', '4933.pkl', '6529.pkl', '4301.pkl', '4692.pkl', '8921.pkl', '3927.pkl', '6601.pkl', '10544.pkl', '3325.pkl', '8673.pkl', '5077.pkl', '2567.pkl', '1958.pkl', '8560.pkl', '99.pkl', '6319.pkl', '6308.pkl', '12163.pkl', '9174.pkl', '8734.pkl', '10628.pkl', '12470.pkl', '11650.pkl', '7325.pkl', '4328.pkl', '11285.pkl', '10676.pkl', '2509.pkl', '7057.pkl', '1670.pkl', '937.pkl', '8617.pkl', '7463.pkl', '75.pkl', '1463.pkl', '5925.pkl', '1631.pkl', '5479.pkl', '1340.pkl', '2028.pkl', '4514.pkl', '2855.pkl', '4728.pkl', '4524.pkl', '11926.pkl', '5123.pkl', '10200.pkl', '10424.pkl', '11160.pkl', '4636.pkl', '2072.pkl', '9670.pkl', '8284.pkl', '1199.pkl', '1550.pkl', '9074.pkl', '4815.pkl', '3581.pkl', '5477.pkl', '7435.pkl', '2361.pkl', '10596.pkl', '6337.pkl', '9232.pkl', '9548.pkl', '9024.pkl', '3461.pkl', '8049.pkl', '9616.pkl', '2424.pkl', '3951.pkl', '1114.pkl', '2287.pkl', '1792.pkl', '8293.pkl', '1015.pkl', '3404.pkl', '11411.pkl', '1813.pkl', '6566.pkl', '608.pkl', '7406.pkl', '1073.pkl', '7167.pkl', '2276.pkl', '8820.pkl', '10767.pkl', '8305.pkl', '10225.pkl', '11837.pkl', '10015.pkl', '3169.pkl', '3103.pkl', '1460.pkl', '10340.pkl', '5248.pkl', '1150.pkl', '9471.pkl', '12438.pkl', '2668.pkl', '2633.pkl', '3517.pkl', '11554.pkl', '4717.pkl', '2297.pkl', '2335.pkl', '1166.pkl', '4689.pkl', '5485.pkl', '12448.pkl', '4785.pkl', '6136.pkl', '1326.pkl', '2269.pkl', '3076.pkl', '4263.pkl', '4329.pkl', '8735.pkl', '1764.pkl', '1541.pkl', '2675.pkl', '5343.pkl', '11266.pkl', '1294.pkl', '1770.pkl', '8730.pkl', '8859.pkl', '8405.pkl', '11238.pkl', '10546.pkl', '1828.pkl', '12148.pkl', '803.pkl', '11485.pkl', '7498.pkl', '11727.pkl', '10925.pkl', '10868.pkl', '11460.pkl', '3331.pkl', '6020.pkl', '11388.pkl', '6635.pkl', '10684.pkl', '4190.pkl', '2645.pkl', '10284.pkl', '2955.pkl', '8510.pkl', '7020.pkl', '8941.pkl', '8455.pkl', '4994.pkl', '2630.pkl', '1967.pkl', '8096.pkl', '8646.pkl', '11654.pkl', '8931.pkl', '5515.pkl', '6717.pkl', '10914.pkl', '12114.pkl', '10953.pkl', '7920.pkl', '5633.pkl', '9324.pkl', '2257.pkl', '8291.pkl', '4351.pkl', '9502.pkl', '11988.pkl', '2502.pkl', '9812.pkl', '2680.pkl', '8190.pkl', '8960.pkl', '403.pkl', '9992.pkl', '10448.pkl', '10873.pkl', '3251.pkl', '2200.pkl', '11663.pkl', '5117.pkl', '11326.pkl', '4870.pkl', '2806.pkl', '7115.pkl', '6349.pkl', '1800.pkl', '4081.pkl', '9768.pkl', '1809.pkl', '10268.pkl', '2358.pkl', '4239.pkl', '7399.pkl', '10226.pkl', '7089.pkl', '6654.pkl', '11739.pkl', '4516.pkl', '5506.pkl', '4019.pkl', '9880.pkl', '9822.pkl', '1725.pkl', '12338.pkl', '7351.pkl', '4450.pkl', '9420.pkl', '4386.pkl', '7452.pkl', '12234.pkl', '5024.pkl', '8719.pkl', '1145.pkl', '5208.pkl', '11545.pkl', '6196.pkl', '9141.pkl', '7106.pkl', '6277.pkl', '18.pkl', '11499.pkl', '7909.pkl', '3054.pkl', '8088.pkl', '12064.pkl', '8822.pkl', '11945.pkl', '3887.pkl', '7551.pkl', '932.pkl', '1674.pkl', '2330.pkl', '5520.pkl', '4554.pkl', '8071.pkl', '8462.pkl', '7137.pkl', '4788.pkl', '10978.pkl', '4271.pkl', '5072.pkl', '9920.pkl', '5980.pkl', '5409.pkl', '12396.pkl', '5946.pkl', '11053.pkl', '11257.pkl', '10090.pkl', '2648.pkl', '407.pkl', '4299.pkl', '497.pkl', '1915.pkl', '241.pkl', '5661.pkl', '3207.pkl', '5407.pkl', '6848.pkl', '8095.pkl', '11380.pkl', '8114.pkl', '8605.pkl', '11571.pkl', '11196.pkl', '9136.pkl', '5269.pkl', '7130.pkl', '3512.pkl', '4830.pkl', '9601.pkl', '7362.pkl', '6121.pkl', '10071.pkl', '3183.pkl', '9035.pkl', '8678.pkl', '9086.pkl', '623.pkl', '12161.pkl', '9371.pkl', '8857.pkl', '4573.pkl', '2601.pkl', '2890.pkl', '6569.pkl', '2903.pkl', '9650.pkl', '10749.pkl', '836.pkl', '2773.pkl', '2344.pkl', '8248.pkl', '11997.pkl', '2158.pkl', '11133.pkl', '10467.pkl', '2694.pkl', '9407.pkl', '11457.pkl', '7284.pkl', '11205.pkl', '2224.pkl', '823.pkl', '7143.pkl', '3958.pkl', '10361.pkl', '310.pkl', '10947.pkl', '303.pkl', '6011.pkl', '4665.pkl', '11851.pkl', '6675.pkl', '6032.pkl', '1932.pkl', '9906.pkl', '7576.pkl', '3513.pkl', '9432.pkl', '9525.pkl', '2348.pkl', '7716.pkl', '10860.pkl', '910.pkl', '4720.pkl', '6778.pkl', '7006.pkl', '11333.pkl', '5897.pkl', '8206.pkl', '1258.pkl', '3834.pkl', '11236.pkl', '4215.pkl', '11903.pkl', '9328.pkl', '5995.pkl', '2366.pkl', '1755.pkl', '10501.pkl', '7369.pkl', '8658.pkl', '10057.pkl', '1938.pkl', '2476.pkl', '5093.pkl', '10158.pkl', '2027.pkl', '9400.pkl', '4522.pkl', '2090.pkl', '9029.pkl', '12413.pkl', '7123.pkl', '12437.pkl', '7772.pkl', '2808.pkl', '853.pkl', '713.pkl', '11731.pkl', '2133.pkl', '10400.pkl', '11662.pkl', '3194.pkl', '6681.pkl', '3372.pkl', '722.pkl', '6908.pkl', '10572.pkl', '1119.pkl', '1482.pkl', '5793.pkl', '11610.pkl', '9422.pkl', '5624.pkl', '7897.pkl', '6796.pkl', '2308.pkl', '2144.pkl', '7230.pkl', '11846.pkl', '5312.pkl', '2783.pkl', '5584.pkl', '4433.pkl', '1805.pkl', '6692.pkl', '2466.pkl', '3450.pkl', '9078.pkl', '6372.pkl', '6810.pkl', '4077.pkl', '9526.pkl', '10365.pkl', '1000.pkl', '2347.pkl', '2616.pkl', '3217.pkl', '8739.pkl', '10249.pkl', '1761.pkl', '626.pkl', '1512.pkl', '4232.pkl', '9060.pkl', '19.pkl', '584.pkl', '11828.pkl', '3246.pkl', '8961.pkl', '8765.pkl', '6758.pkl', '5511.pkl', '1498.pkl', '7185.pkl', '11297.pkl', '4211.pkl', '4413.pkl', '7129.pkl', '4181.pkl', '7226.pkl', '3490.pkl', '9466.pkl', '1239.pkl', '5620.pkl', '7516.pkl', '2313.pkl', '1678.pkl', '8544.pkl', '3560.pkl', '12093.pkl', '9351.pkl', '12045.pkl', '5727.pkl', '10666.pkl', '411.pkl', '5258.pkl', '10024.pkl', '3419.pkl', '912.pkl', '8489.pkl', '4736.pkl', '1181.pkl', '166.pkl', '11723.pkl', '7670.pkl', '5905.pkl', '3567.pkl', '12398.pkl', '6150.pkl', '11028.pkl', '4758.pkl', '4756.pkl', '10060.pkl', '9006.pkl', '10318.pkl', '4146.pkl', '9363.pkl', '10260.pkl', '4890.pkl', '5185.pkl', '4787.pkl', '12253.pkl', '5491.pkl', '5209.pkl', '9392.pkl', '6231.pkl', '1824.pkl', '9118.pkl', '6461.pkl', '40.pkl', '10732.pkl', '1016.pkl', '2919.pkl', '5593.pkl', '4178.pkl', '2972.pkl', '12357.pkl', '10725.pkl', '10804.pkl', '1939.pkl', '5769.pkl', '1176.pkl', '5335.pkl', '5840.pkl', '5933.pkl', '4491.pkl', '2868.pkl', '5051.pkl', '1825.pkl', '9275.pkl', '10867.pkl', '9165.pkl', '9075.pkl', '11718.pkl', '3433.pkl', '11233.pkl', '7262.pkl', '7774.pkl', '6012.pkl', '6449.pkl', '4485.pkl', '3020.pkl', '1196.pkl', '6056.pkl', '2906.pkl', '2950.pkl', '6363.pkl', '3110.pkl', '5138.pkl', '10208.pkl', '8496.pkl', '1578.pkl', '6899.pkl', '8821.pkl', '8722.pkl', '7308.pkl', '12423.pkl', '3046.pkl', '9474.pkl', '12254.pkl', '2666.pkl', '848.pkl', '9748.pkl', '1900.pkl', '6295.pkl', '1574.pkl', '4277.pkl', '10727.pkl', '7532.pkl', '12478.pkl', '11398.pkl', '7055.pkl', '5662.pkl', '11847.pkl', '8616.pkl', '4304.pkl', '1446.pkl', '8043.pkl', '7895.pkl', '4403.pkl', '12019.pkl', '8799.pkl', '7422.pkl', '9112.pkl', '11206.pkl', '9808.pkl', '3763.pkl', '426.pkl', '2295.pkl', '8352.pkl', '9803.pkl', '1456.pkl', '2989.pkl', '11736.pkl', '3977.pkl', '698.pkl', '9373.pkl', '3592.pkl', '10391.pkl', '2490.pkl', '6156.pkl', '12142.pkl', '6285.pkl', '1426.pkl', '9877.pkl', '8944.pkl', '2908.pkl', '8422.pkl', '8069.pkl', '3322.pkl', '3478.pkl', '11643.pkl', '8843.pkl', '8899.pkl', '11838.pkl', '568.pkl', '10308.pkl', '7355.pkl', '7656.pkl', '7717.pkl', '2900.pkl', '2141.pkl', '11252.pkl', '2332.pkl', '2729.pkl', '7471.pkl', '10857.pkl', '6990.pkl', '6739.pkl', '12368.pkl', '5213.pkl', '5550.pkl', '10619.pkl', '6997.pkl', '11797.pkl', '2073.pkl', '11300.pkl', '12205.pkl', '1723.pkl', '9766.pkl', '5089.pkl', '8138.pkl', '9049.pkl', '7038.pkl', '6371.pkl', '11320.pkl', '344.pkl', '9468.pkl', '8764.pkl', '3116.pkl', '11114.pkl', '7891.pkl', '10193.pkl', '8260.pkl', '964.pkl', '11689.pkl', '2957.pkl', '9001.pkl', '529.pkl', '8877.pkl', '10664.pkl', '10630.pkl', '2480.pkl', '5712.pkl', '629.pkl', '5358.pkl', '2530.pkl', '8153.pkl', '10255.pkl', '11015.pkl', '2440.pkl', '650.pkl', '2192.pkl', '8978.pkl', '9256.pkl', '4098.pkl', '2493.

In [ ]:
len(dataset)

7149

In [ ]:
import numpy as np

def calculate_metrics(outputs, labels):

    probs = torch.sigmoid(outputs).detach().cpu().numpy().flatten()
    preds = (probs > 0.5).astype(int)

    labels_np = labels.detach().cpu().numpy().flatten()
    outputs = outputs.detach().cpu().numpy()

    print(np.unique(preds))

    metrics = {}

    metrics['accuracy'] = accuracy_score(labels_np, preds)

    metrics['recall'] = recall_score(labels_np, preds, zero_division=0)

    metrics['roc_auc'] = roc_auc_score(labels_np, outputs)

    metrics['pr_auc'] = average_precision_score(labels_np, outputs)

    return metrics

In [ ]:
def evaluate(model, data_loader, criterion, device='cpu'):

    model.eval()
    total_loss = 0
    all_outputs = []
    all_labels = []

    with torch.no_grad():
        for graphs, labels in data_loader:

            graphs = graphs.to(device)
            labels = labels.to(device)

            outputs = model(graphs.x, graphs.edge_index, graphs.edge_weight, graphs.batch)
            #outputs = model(graphs.x, graphs.edge_index, graphs.batch)
            loss = criterion(outputs, labels)

            total_loss += loss.item()

            all_outputs.append(outputs)
            all_labels.append(labels)


    all_outputs = torch.cat(all_outputs, dim=0)
    all_labels = torch.cat(all_labels, dim=0)

    metrics = calculate_metrics(all_outputs, all_labels)
    avg_loss = total_loss / len(data_loader)

    return avg_loss, metrics

In [ ]:
!pip install early-stopping-pytorch

In [ ]:
from sklearn.metrics import accuracy_score, recall_score, roc_auc_score, average_precision_score
from early_stopping_pytorch import EarlyStopping

early_stopping = EarlyStopping(patience=7, verbose=True)

model = GNNBinaryClassifier(input_dim=768, hidden_dim=64)
criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

losses = []

num_epochs = 10

val_losses = []


iter = 0
while True:

  all_train_outputs = []
  all_train_labels = []
  losses = []

  for batch_idx, (graphs, labels) in enumerate(train_loader):
      outputs = model(graphs.x, graphs.edge_index, graphs.edge_weight, graphs.batch)
      loss = criterion(outputs, labels)

      optimizer.zero_grad()
      loss.backward()
      optimizer.step()

      all_train_outputs.append(outputs)
      all_train_labels.append(labels)

      losses.append(loss.item())

  all_train_outputs = torch.cat(all_train_outputs, dim=0)
  all_train_labels = torch.cat(all_train_labels, dim=0)

  mean_loss = np.mean(np.array(losses))
  train_metrics = calculate_metrics(all_train_outputs, all_train_labels)

  print(f"Epoch {iter+1}/{num_epochs}")
  print(f"{'='*60}")
  print(f"Train Loss: {mean_loss:.4f}")
  print(f"\nTrain Metrics:")
  print(f"  Accuracy: {train_metrics['accuracy']:.4f}")
  print(f"  Recall:   {train_metrics['recall']:.4f}")
  print(f"  ROC-AUC:  {train_metrics['roc_auc']:.4f}")
  print(f"  PR-AUC:   {train_metrics['pr_auc']:.4f}")

  val_loss, val_metrics = evaluate(model, val_loader, criterion)
  val_losses.append(val_loss)

  print(f"\nVal Metrics:")
  print(f"  Accuracy: {val_metrics['accuracy']:.4f}")
  print(f"  Recall:   {val_metrics['recall']:.4f}")
  print(f"  ROC-AUC:  {val_metrics['roc_auc']:.4f}")
  print(f"  PR-AUC:   {val_metrics['pr_auc']:.4f}")
  print(f"{'='*60}\n")

  iter += 1

  early_stopping(val_loss, model)
  if early_stopping.early_stop:
      print("Early stopping triggered")
      break

[0]
Epoch 1/10
============================================================
Train Loss: 0.4651

Train Metrics:
  Accuracy: 0.8147
  Recall:   0.0000
  ROC-AUC:  0.6420
  PR-AUC:   0.2520
[0]

Val Metrics:
  Accuracy: 0.7969
  Recall:   0.0000
  ROC-AUC:  0.7321
  PR-AUC:   0.3923
============================================================

Validation loss decreased (inf --> 0.451701).  Saving model ...
[0 1]
Epoch 2/10
============================================================
Train Loss: 0.4291

Train Metrics:
  Accuracy: 0.8145
  Recall:   0.0162
  ROC-AUC:  0.7315
  PR-AUC:   0.3773
[0 1]

Val Metrics:
  Accuracy: 0.7969
  Recall:   0.0345
  ROC-AUC:  0.7398
  PR-AUC:   0.4182
============================================================

Validation loss decreased (0.451701 --> 0.444879).  Saving model ...
[0 1]
Epoch 3/10
============================================================
Train Loss: 0.4130

Train Metrics:
  Accuracy: 0.8175
  Recall:   0.0809
  ROC-AUC:  0.7557
  PR-AUC:   0.4219
[0 1]

Val Metrics:
  Accuracy: 0.8081
  Recall:   0.1655
  ROC-AUC:  0.7525
  PR-AUC:   0.4502
============================================================

Validation loss decreased (0.444879 --> 0.434857).  Saving model ...
[0 1]
Epoch 4/10
============================================================
Train Loss: 0.4021

Train Metrics:
  Accuracy: 0.8265
  Recall:   0.1510
  ROC-AUC:  0.7737
  PR-AUC:   0.4566
[0 1]

Val Metrics:
  Accuracy: 0.8095
  Recall:   0.1448
  ROC-AUC:  0.7580
  PR-AUC:   0.4463
============================================================

EarlyStopping counter: 1 out of 7
[0 1]
Epoch 5/10
============================================================
Train Loss: 0.3944

Train Metrics:
  Accuracy: 0.8327
  Recall:   0.2060
  ROC-AUC:  0.7856
  PR-AUC:   0.4766
[0 1]

Val Metrics:
  Accuracy: 0.8081
  Recall:   0.2207
  ROC-AUC:  0.7607
  PR-AUC:   0.4610
============================================================

Validation loss decreased (0.434857 --> 0.433503).  Saving model ...
[0 1]
Epoch 6/10
============================================================
Train Loss: 0.3852

Train Metrics:
  Accuracy: 0.8331
  Recall:   0.2233
  ROC-AUC:  0.8004
  PR-AUC:   0.5092
[0 1]

Val Metrics:
  Accuracy: 0.8109
  Recall:   0.3103
  ROC-AUC:  0.7583
  PR-AUC:   0.4459
============================================================

EarlyStopping counter: 1 out of 7
[0 1]
Epoch 7/10
============================================================
Train Loss: 0.3689

Train Metrics:
  Accuracy: 0.8427
  Recall:   0.2762
  ROC-AUC:  0.8191
  PR-AUC:   0.5490
[0 1]

Val Metrics:
  Accuracy: 0.8053
  Recall:   0.2690
  ROC-AUC:  0.7480
  PR-AUC:   0.4170
============================================================

EarlyStopping counter: 2 out of 7
[0 1]
Epoch 8/10
============================================================
Train Loss: 0.3539

Train Metrics:
  Accuracy: 0.8493
  Recall:   0.3193
  ROC-AUC:  0.8398
  PR-AUC:   0.5922
[0 1]

Val Metrics:
  Accuracy: 0.7997
  Recall:   0.2690
  ROC-AUC:  0.7395
  PR-AUC:   0.4019
============================================================

EarlyStopping counter: 3 out of 7
[0 1]
Epoch 9/10
============================================================
Train Loss: 0.3317

Train Metrics:
  Accuracy: 0.8593
  Recall:   0.3819
  ROC-AUC:  0.8616
  PR-AUC:   0.6357
[0 1]

Val Metrics:
  Accuracy: 0.7955
  Recall:   0.1586
  ROC-AUC:  0.7428
  PR-AUC:   0.4035
============================================================

EarlyStopping counter: 4 out of 7
[0 1]
Epoch 10/10
============================================================
Train Loss: 0.3129

Train Metrics:
  Accuracy: 0.8667
  Recall:   0.4132
  ROC-AUC:  0.8779
  PR-AUC:   0.6832
[0 1]

Val Metrics:
  Accuracy: 0.7801
  Recall:   0.3103
  ROC-AUC:  0.7406
  PR-AUC:   0.3966
============================================================

EarlyStopping counter: 5 out of 7
[0 1]
Epoch 11/10
============================================================
Train Loss: 0.2902

Train Metrics:
  Accuracy: 0.8787
  Recall:   0.4725
  ROC-AUC:  0.8984
  PR-AUC:   0.7242
[0 1]

Val Metrics:
  Accuracy: 0.7801
  Recall:   0.3103
  ROC-AUC:  0.7218
  PR-AUC:   0.3543
============================================================

EarlyStopping counter: 6 out of 7
[0 1]
Epoch 12/10
============================================================
Train Loss: 0.2657

Train Metrics:
  Accuracy: 0.8867
  Recall:   0.5264
  ROC-AUC:  0.9183
  PR-AUC:   0.7662
[0 1]

Val Metrics:
  Accuracy: 0.7815
  Recall:   0.1655
  ROC-AUC:  0.7295
  PR-AUC:   0.3673
============================================================

EarlyStopping counter: 7 out of 7
Early stopping triggered

In [ ]:
test_loss, test_metrics = evaluate(model, test_loader, criterion)
print("TEST SET RESULTS:")
for metric, value in test_metrics.items():
    print(f"  {metric.upper()}: {value:.4f}")

[0 1]
TEST SET RESULTS:
  ACCURACY: 0.7980
  RECALL: 0.1661
  ROC_AUC: 0.7180
  PR_AUC: 0.3734

In [ ]:
torch.save(model.state_dict(), 'best_math_qwen2.5_32B_attention_graphs_model_32_bs_weights.pth')

torch.save(model, 'best_math_qwen2.5_32B_attention_graphs_full_model_32_bs.pth')